import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_KEY } from './config.js';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const money=v=>v==null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function monthDue(day){const n=new Date(),y=n.getFullYear(),m=n.getMonth();return new Date(y,m,Math.min(Number(day||1),new Date(y,m+1,0).getDate()));}
function ymd(d){const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function daysTo(d){const a=new Date();a.setHours(0,0,0,0);const b=new Date(d);b.setHours(0,0,0,0);return Math.ceil((b-a)/86400000)}
async function state(){const {data:{session}}=await sb.auth.getSession();if(!session)return null;const uid=session.user.id;const {data:coach}=await sb.from('coach_users').select('user_id').eq('user_id',uid).maybeSingle();if(coach){const {data:students}=await sb.from('profiles').select('user_id,full_name,is_active').neq('user_id',uid);const ids=(students||[]).filter(x=>x.is_active!==false).map(x=>x.user_id);if(!ids.length)return {coach:true,total:0,ok:0,soon:0,late:0};const [{data:settings},{data:payments}]=await Promise.all([sb.from('student_billing_settings').select('*').in('user_id',ids),sb.from('student_payments').select('*').in('user_id',ids)]);let ok=0,soon=0,late=0;for(const id of ids){const s=(settings||[]).find(x=>x.user_id===id)||{billing_day:1};const due=monthDue(s.billing_day);const dueS=ymd(due);const paid=(payments||[]).some(p=>p.user_id===id&&p.status==='paid'&&String(p.due_date).slice(0,7)===dueS.slice(0,7));if(paid){ok++;continue}const delta=daysTo(due);if(delta<0)late++;else if(delta<=5)soon++;else ok++;}return {coach:true,total:ids.length,ok,soon,late};}
const {data:s}=await sb.from('student_billing_settings').select('*').eq('user_id',uid).maybeSingle();if(!s||s.reminders_enabled===false)return {coach:false,hidden:true};const due=monthDue(s.billing_day),dueS=ymd(due);const {data:p}=await sb.from('student_payments').select('*').eq('user_id',uid).gte('due_date',dueS.slice(0,7)+'-01').lte('due_date',dueS.slice(0,7)+'-31').order('due_date',{ascending:false}).limit(1).maybeSingle();const paid=p?.status==='paid';const delta=daysTo(due);return {coach:false,paid,delta,due:dueS,amount:s.monthly_amount};}
function html(s){if(!s||s.hidden)return '';if(s.coach)return `<section class="billing-v11" data-billing-v11><div class="billing-title"><div><h3>Mensalidades</h3><p>Visão deste mês</p></div><div class="billing-icon">▣</div></div><div class="billing-summary"><div class="billing-kpi"><strong>${s.ok}</strong><span>Em dia</span></div><div class="billing-kpi"><strong>${s.soon}</strong><span>Próx. venc.</span></div><div class="billing-kpi"><strong>${s.late}</strong><span>Pendentes</span></div></div></section>`;let cls='ok',label='Mensalidade em dia ✓';if(!s.paid&&s.delta<0){cls='late';label=`Mensalidade vencida há ${Math.abs(s.delta)} dia(s)`}else if(!s.paid&&s.delta<=5){cls='soon';label=`Sua mensalidade vence em ${s.delta===0?'hoje':s.delta+' dia(s)'}`}else if(!s.paid){cls='ok';label='Próxima mensalidade'}return `<section class="billing-v11" data-billing-v11><div class="billing-title"><div><h3>Mensalidade da consultoria</h3><p>Vencimento: ${fmt(s.due)} · ${money(s.amount)}</p></div><div class="billing-icon">▣</div></div><span class="billing-status ${cls}">${label}</span></section>`}
let cached=null,busy=false;async function inject(){if(busy)return;const app=document.querySelector('#app');if(!app||!app.textContent.trim()||app.querySelector('[data-billing-v11]'))return;if(!/início|inicio|olá|ola|painel|evolução corporal/i.test(app.textContent))return;busy=true;try{cached=await state();if(!cached)return;const main=app.querySelector('main');if(!main)return;const wrap=document.createElement('div');wrap.innerHTML=html(cached);const el=wrap.firstElementChild;if(el)main.insertBefore(el,main.children[1]||null);}catch(e){console.warn('billing-v11',e)}finally{busy=false}}
new MutationObserver(()=>setTimeout(inject,60)).observe(document.documentElement,{childList:true,subtree:true});
setTimeout(inject,500);